In [1]:
# installations
# Install yfinance inside the JupyterLab environment
import sys
!{sys.executable} -m pip install yfinance --upgrade --use-pep517

Requirement already satisfied: yfinance in c:\users\aneli\anaconda3\lib\site-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.7 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\aneli\anaconda3\lib\site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\aneli\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\aneli\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\aneli\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.6.15)
Requirement already satisfied: pycparser in c:\users\aneli\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aneli\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aneli\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aneli\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aneli\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aneli\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aneli\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)

In [2]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

# Predicting Bitcoin Prices Using Machine Learning

## Introduction / Abstract

Given historical Bitcoin price data, can we predict the price for the next few days?

## Dataset & Preprocessing

In [3]:
# Read the Kaggle dataset containing Bitcoin historical data
btc_data = pd.read_csv("data/btcusd_1-min_data.csv")

In [4]:
btc_data

            Timestamp       Open       High        Low      Close    Volume
0        1.325412e+09       4.58       4.58       4.58       4.58  0.000000
1        1.325412e+09       4.58       4.58       4.58       4.58  0.000000
2        1.325412e+09       4.58       4.58       4.58       4.58  0.000000
3        1.325412e+09       4.58       4.58       4.58       4.58  0.000000
4        1.325412e+09       4.58       4.58       4.58       4.58  0.000000
...               ...        ...        ...        ...        ...       ...
7251512  1.760572e+09  110716.00  110740.00  110716.00  110740.00  6.220424
7251513  1.760572e+09  110740.00  110740.00  110716.00  110716.00  3.255152
7251514  1.760572e+09  110716.00  110717.00  110716.00  110717.00  5.158200
7251515  1.760573e+09  110716.00  110740.00  110716.00  110740.00  1.173851
7251516  1.760573e+09  110740.00  110763.00  110740.00  110763.00  1.370955

[7251517 rows x 6 columns]

In [5]:
# Convert timestamp to datetime
btc_data['Timestamp'] = pd.to_datetime(btc_data['Timestamp'], unit='s')

In [6]:
btc_data.tail()

                  Timestamp      Open      High       Low     Close    Volume
7251512 2025-10-15 23:53:00  110716.0  110740.0  110716.0  110740.0  6.220424
7251513 2025-10-15 23:54:00  110740.0  110740.0  110716.0  110716.0  3.255152
7251514 2025-10-15 23:55:00  110716.0  110717.0  110716.0  110717.0  5.158200
7251515 2025-10-15 23:56:00  110716.0  110740.0  110716.0  110740.0  1.173851
7251516 2025-10-15 23:57:00  110740.0  110763.0  110740.0  110763.0  1.370955

In [7]:
btc_data.set_index('Timestamp', inplace=True)

In [8]:
# btc_data = btc_data.resample('1D')

In [9]:
# Daily resampling
btc_data_daily = btc_data.resample('1D').agg({
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum'
})

In [10]:
btc_data[btc_data.index.astype(str).str.startswith("2025-10-15 00:00:00")].describe()

           Open      High       Low     Close    Volume
count       1.0       1.0       1.0       1.0  1.000000
mean   113077.0  113091.0  113041.0  113081.0  0.874398
std         NaN       NaN       NaN       NaN       NaN
min    113077.0  113091.0  113041.0  113081.0  0.874398
25%    113077.0  113091.0  113041.0  113081.0  0.874398
50%    113077.0  113091.0  113041.0  113081.0  0.874398
75%    113077.0  113091.0  113041.0  113081.0  0.874398
max    113077.0  113091.0  113041.0  113081.0  0.874398

In [11]:
btc_data_daily.tail()

                Open      High       Low     Close       Volume
Timestamp
2025-10-11  112989.0  113444.0  109711.0  110764.0  2954.913907
2025-10-12  110769.0  115854.0  109711.0  115090.0  2969.343862
2025-10-13  115089.0  116035.0  113751.0  115265.0  1947.580681
2025-10-14  115275.0  115508.0  109971.0  113078.0  2253.667329
2025-10-15  113077.0  113655.0  110217.0  110763.0  2021.923209

In [12]:
# Shape of the daily BTC dataset
btc_data_daily.shape

(5037, 5)

Now there are much less records that is why some additional measurements will be included.

In [13]:
# Check for null values in the original set
btc_data.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [14]:
# Check for null values in the resampled dataset
btc_data_daily.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5037 entries, 2012-01-01 to 2025-10-15
Freq: D
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5037 non-null   float64
 1   High    5037 non-null   float64
 2   Low     5037 non-null   float64
 3   Close   5037 non-null   float64
 4   Volume  5037 non-null   float64
dtypes: float64(5)
memory usage: 236.1 KB

There are no null values which is due to the fact that all the data has been fetched from a reliable API.

### Columns

<b>A short description of the features (a standard stock measurement; also called OHLCV): </b>
- Open --> the price of BTC when the day started
- High --> the highest price of BTC in the mentioned day
- Low --> the lowest price of BTC in the mentioned day
- Close --> the price of BTC when the day ended
- Volume --> the total amount of BTC which were traded

<br> </br>
<b>Features to be Added:</b>
- RSI --> 
- other -->

## EDA - Exploratory Data Analysis

In [ ]:
# a line chart showing the ups and downs
# box plots for all features
# correlation between the features
# when are the price peaks